version: '3.3'

services:
  db:
    image: postgres:15
    container_name: foodgram-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/.env

  backend:
    container_name: foodgram-backend
    build: ../backend
    volumes:
      - ../backend/:/app/
      - static_data:/app/static/           # для collectstatic
      - media_data:/app/media/             # для пользовательских медиа
    depends_on:
      - db
    env_file:
      - ../backend/.env

  nginx:
    container_name: foodgram-proxy
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/backend_static/
      - media_data:/media/
      - ../docs/:/usr/share/nginx/html/api/docs/

volumes:
  postgres_data:
  static_data:
  media_data: