apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: amqp
    port: {{ .Values.service.amqpPort }}
    targetPort: amqp
    protocol: TCP
  - name: management
    port: {{ .Values.service.managementPort }}
    targetPort: management
    protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: amqp
    port: {{ .Values.service.amqpPort }}
    targetPort: amqp
    protocol: TCP
  - name: management
    port: {{ .Values.service.managementPort }}
    targetPort: management
    protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
