apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.headless.type }}
  clusterIP: {{ .Values.service.headless.clusterIP }}
  ports:
  - port: {{ .Values.service.headless.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
