{{- if .Values.service.loadbalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.loadbalancer.type }}
  ports:
  - port: {{ .Values.service.loadbalancer.port }}
    targetPort: redis
    protocol: TCP
    name: redis
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
{{- end }}
