---
apiVersion: v1
kind: Secret
metadata:
  name: foodgram-secrets
  namespace: foodgram
type: Opaque
stringData:
  POSTGRES_DB: "foodgram"
  POSTGRES_USER: "foodgram_user"
  POSTGRES_PASSWORD: "change_me_in_production"
  
  DJANGO_SECRET_KEY: "django-insecure-change-this-in-production-secretkey"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: foodgram
type: Opaque
stringData:
  POSTGRES_DB: "foodgram"
  POSTGRES_USER: "foodgram_user"
  POSTGRES_PASSWORD: "change_me_in_production"
